<?php
// 'host' for the PostgreSQL server
$sqlConf->host      = "localhost";

// default port for PostgreSQL is "5432"
$sqlConf->port      = 5432;

// set the database name for the connection
$sqlConf->dbname    = "mail";

// set the username for PostgreSQL database
$sqlConf->user      = "mailAuth_user";

// password for the PostgreSQL database
$sqlConf->password  = "maiAuth_pass";

$mail_server_ip     = 'localhost';
?>
